Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
